networks:
    # Allow the use of traefik in other docker-compose.yml files
    web:
        external: true

services:
  resonance_sri_service:
    image: sri_service:latest
    ports: # Forward streamlit port
      - 8501:8501
    networks:
      - "web"
    restart: always
    labels:
      - traefik.http.routers.resonance_sri_service.entrypoints=http,https
      - traefik.http.routers.resonance_sri_service.rule=Host(`sri-resonance.trialog.com`)
      - traefik.http.routers.resonance_sri_service.tls=true
      - traefik.http.routers.resonance_sri_service.tls.certresolver=trialog
      - traefik.http.routers.resonance_sri_service.middlewares=auth_sri # Create basic-authentication module named "auth_sri"
      - traefik.http.middlewares.auth_sri.basicauth.users=vincent.maury:$$2y$$14$$eL1Ai9pPCBS04iK8LKMmUen92ONy1JrZknE8E3pBrxjp6o.WIMlOm,trialog:$$2y$$14$$UAcyzgf0sQaAvsDjT1/8N.YCdamkXTgJzFxV7vbfOGhSsBWKlu1Vm,external_1:$$2y$$14$$f7RjmYwQo/pCJusLb.N/1.FI0nHw72/SorjavFqlavGW8SZE5mYza
# Encrypted password are generated with "htpasswd -n -B -C 14 user-name" + escaping the dollars signs

